name: Validate

on: [push, pull_request]


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Hatch
      run: pip install hatch

    - name: Install project dependencies
      run: hatch run pip install -e .[dev]

    - name: Run Ruff (linting)
      run: hatch run ruff check src/views_challenge tests

    - name: Run pytest (testing)
      run: hatch run pytest